version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=auuntoo
      - POSTGRES_USER=auuntoo
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080